### ISSUE TITLE
Prevent Content Cafe coverage provider from processing batches

### ISSUE THREAD

**Issue by courte** [NYPL-Simplified/metadata_wrangler#25]
From #22 line notes: I think we don't actually want to get Content Cafe coverage for every single ISBN the metadata wrangler knows about. We only want to get coverage for ISBNs that a client specifically asks about. However, I think this code is fine because we're not going to actually run this like a normal coverage provider, we're going to use ensure_coverage on individual ISBNs.

Prevent Content Cafe from processing batches or better define how those batches should be supplied.

**Comment by leonardr** [comment]
I don't think there's any work to do here. If for some reason we decide to run the coverage provider as a normal coverage provider, it should work. We just don't need to do that right now.
