### ISSUE TITLE
Some LicensePools on metadata wrangler are missing a presentation edition

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/metadata_wrangler#76]
This URL gives me a 502:

http://metadata.alpha.librarysimplified.org/lookup?urn=urn%3Alibrarysimplified.org%2Fterms%2Fid%2FOverdrive%2520ID%2Fe66c531d-1975-490a-9b54-07c8245c2278

I see a number of problems here:

* When this sort of error happens it's supposed to result in a <simplified:message> explaining the problem, not a 502 error that wrecks the whole feed.
* The problem happens because the LicensePool has no presentation edition, which isn't supposed to happen. (The Work does have a presentation edition.) This is probably the only part of this issue that's a problem with the metadata wrangler code -- how did this happen?
* If for whatever reason the LicensePool has no presentation edition but the Work does have a presentation edition, this should be logged as an error but we should go ahead and use the Work's presentation edition to avoid a crash.

**Comment by courte** [comment]
This URL no longer gives a 502, but I'm not sure if the underlying problem has been resolved.

**Comment by leonardr** [comment]
I think it has been resolved. There are no LicensePools on metadata that have an Identifier and a Work but no presentation edition.
